apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app-deployment
  labels:
    app: {{ .Values.defaultLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.defaultLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.defaultLabel }}
    spec:
      containers:
      - name: go-web-app-con
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      # imagePullSecrets:
      # - name: <docker-secrets-name>  # pulling image from private registry with secrets
      # cmd to create secrets = [ kubectl create secret docker-registry docker-secrets --docker-server=https://index.docker.io/v1/ --docker-username=ExamplaName --docker-password=ExamplePassword --docker-email=example@gmail.com ]
