apiVersion: v1
kind: Service
metadata:
  name: go-web-app-svc
  labels:
    app: {{ .Values.defaultLabel }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.defaultLabel }}
  type: {{ .Values.service.type }}
