name: Build
on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  sonar:
    # if: github.ref == 'refs/heads/main'
    name: SonarCloud
    runs-on: ubuntu-24.04
    environment: dev
    steps:
    - 
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref}}
    - 
      name: Sonar Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  app:
    runs-on: ubuntu-24.04
    environment: dev
    needs: [sonar]
    steps:
    - 
      name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - 
      name: Setup Go Environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'
    -
      name: Install PM2
      run: npm install -g pm2
    - 
      name: Build App
      run: go build -o main .
    - 
      name: Test App
      run: go test
    - 
      name: Deploy App
      run: pm2 start "./main" --name "go-web-app"
    # - 
    #   name: Upload Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-artifact
    #     paths: ./main

  Docker:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    environment: dev
    needs: [app]
    steps:
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Extract Metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: |
          ${{ vars.DOCKERHUB_USERNAME }}/go-web-app
        tags: |
          type=semver,pattern={{version}}
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
