name: Build
on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  SonarQube-Code-Analysis:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    environment: dev
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref}}
    - name: Sonar Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Code-Quality-Check:
    runs-on: ubuntu-24.04
    environment: dev
    needs: [SonarQube-Code-Analysis]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2

  Build-App-For-Dev:
    runs-on: ubuntu-24.04
    environment: dev
    needs: [Code-Quality-Check]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup Go Environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'
    - name: Install PM2
      run: npm install -g pm2
    - name: Build
      run: go build -o main .
    - name: Test
      run: go test
    # - 
    #   name: Upload Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-artifact
    #     paths: ./main

  Push-To-Docker-Registry:
    runs-on: ubuntu-24.04
    environment: dev
    needs: [Build-App-For-Dev]
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/go-web-app:1.${{ github.run_number }}.${{ github.run_attempt}}
