name: Go-Web-App Workflow
on:
  push:
    branches: [main, dev]
  pull_request:
    types: [synchronize]
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  actions: read
  contents: read

jobs:

  SonarQube-Code-Analysis:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    environment: dev
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref}}
    - name: Sonar Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Code-Quality-Check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2

  Build-App-For-Dev:
    runs-on: ubuntu-24.04
    environment: dev
    needs: [SonarQube-Code-Analysis]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup Go Environment
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Install PM2
      run: npm install -g pm2
    - name: Build
      run: go build -o main .
    - name: Test
      run: go test
    # - 
    #   name: Upload Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-artifact
    #     paths: ./main

  Image-Vulnerability-Check:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/develop'
    needs: [Build-App-For-Dev]
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
            push: false
            tags: ${{ vars.DOCKERHUB_USERNAME }}/go-web-app:1.${{ github.run_number }}.${{ github.run_attempt}}
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/go-web-app:1.${{ github.run_number }}.${{ github.run_attempt}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          output: trivy-report.txt
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-report.txt
      
  Push-To-Docker-Registry:
    runs-on: ubuntu-24.04
    environment: dev
    needs: [Image-Vulnerability-Check]
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/go-web-app:1.${{ github.run_number }}.${{ github.run_attempt}}
  